version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: .docker/dev.dockerfile
    image: file-manager-server-dev
    container_name: file-manager-server-dev
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - './server/src:/usr/src/app/src'
